### ISSUE TITLE
Investigate authentication improvements

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#1]
From https://github.com/hotosm/tech/issues/98:

> improve auth and login. Make it easier to deploy with auth enabled plus consider user accounts or admin + data collector access.

Should ensure deployment with SSL as well.

**Comment by willemarcel** [comment]
The first step of authentication is ready:
* added [passport-local](https://github.com/jaredhanson/passport-local/) to manage authentication
* added login/logout views

The users are defined in the `util/users.json` file.

Now I'm going to implement the views permissions with the [permissions](https://github.com/tenodi/permission) lib. That package allow us to define permissions by role in each view

**Comment by willemarcel** [comment]
The code is available in the [auth-login](https://github.com/hotosm/OpenMapKitServer/tree/auth-login) branch

**Comment by PaulUithol** [comment]
Question (I haven't googled this yet), what methods of authentication does ODK/OMK support? As we'll need to support both web users and data collection apps.

**Comment by willemarcel** [comment]
@PaulUithol I believe ODK supports only basic authentication

**Comment by mojodna** [comment]
ODK 1.x supports Basic Authentication over HTTPS connections, Digest Authentication over HTTP(S). ODK Briefcase is a good tool to test on a desktop if you don't have ODK on an Android phone handy.

**Comment by danbjoseph** [comment]
Is this at the OMKServer 'app' level or at the POSM level (i.e. using posm-build to install omkserver)? When accessing the POSM dashboard or accessing OMKServer?
<img width="230" alt="screen shot 2018-01-29 at 12 36 42 pm" src="https://user-images.githubusercontent.com/4806884/35508589-3257e556-04f1-11e8-929a-4fbfbd71f81a.png">
