### ISSUE TITLE
Creating CloudFormation based OpenMapKitServer stacks

### ISSUE THREAD

**Issue by arunasank** [hotosm/OpenMapKitServer#103]
Let's start work on this after https://github.com/hotosm/OpenMapKitServer/pull/102 gets merged. 

This will fix the following, from https://github.com/hotosm/OpenMapKitServer/issues/93

> Task  | Description | Expected timeline | Owner | Status
> ----------|----------|----------|----------|----------|
> **Set up all our OMK stacks using CloudFormation** | Make a detailed plan for deleting existing EBS environments, and setting up OMK stacks on CloudFormation, to ensure that the process is seamless and secure, and we don't accidentally lose data | End Feb | @ramyaragupathy|

👋 @ramyaragupathy! We are going to create 7 stacks, with the following stack-names:
* guatemala
* kampala
* nepal
* opencitiesafrica
* opencitiesliberia
* tanzania
* zambia

## What you need
The CloudFormation template has the following stack parameters. Some of these you need to retrieve from the 
* **EBS console** - For example, the configuration parameters for the `guatemala-1` stack are available [here](https://console.aws.amazon.com/elasticbeanstalk/home?region=us-east-1#/environment/configuration?applicationName=OpenMapKitServer&environmentId=e-3cifxttga6)
* **Existing stack template** - `s3://hot-cfn-config/OpenMapKitServer/OpenMapKitServer-stagingA-us-east-1.cfn.json`

Parameter | Retrieval
--------------|---------------
ELBSecurityGroup | Template
ELBSubnets | Template
EC2SecurityGroup | Template
S3Bucket | EBS
S3Prefix | EBS
OpenMapKitVersion | Template
EnableS3Sync | EBS
NodeEnvironment | Template
SSLCertificateIdentifier | Template
UsersS3Bucket | Template 
VpcId | Template

## Creation
* `git checkout cloudformation`
* `npm install`
* `cfn-config create <stack-name> cloudformation/OpenMapKitServer.template.js -c hot-cfn-config -t hot-cfn-config` - This will prompt you for the stack parameters in the same way as the hot-qa-tiles stack did.

## Verification
Once the stack is created, verify that the stack works as expected by:
* Navigating to the list of [Load Balancers](https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#LoadBalancers:sort=loadBalancerName), and identifying our stack load balancer. Pick out the Load Balancer DNS from the Load Balancer description, and check to see if it returns an OMK webpage.
* If the above looks good, compare the response received with the response from the OpenMapKitServer production instance for that stack. They should be exactly similar. 
* Load Test with swarm. https://github.com/hotosm/swarm/issues/1

## Updating the Route53 DNS
If the above look good, manually change the Route 53 record set for a production instance to point to the ELB DNS. To do this:
* Navigate to the Route 53 console -> Hosted Zones -> hotosm.org (Click the link): You should see a set of records that point to the OMK instance you're working on. A record set is named the same as the OMK production website.  When you select the record set you should see the option to fill out an `Alias Target`. Enter the ELB DNS address in this space.
* Check if the website still works when accessed through the ELB DNS

## Deleting EBS stacks
Once you've verified that the servers are functional:
`aws elasticbeanstalk terminate-environment --environment-name <stack-name>` to terminate the EBS environment.

@ramyaragupathy I realised that there's a lot of stacks here. It might be nicer to pair on this! 🙂

**Comment by willemarcel** [comment]
It looks very nice... After the merges, we need to create new releases and configure the versions on the cfn config

**Comment by arunasank** [comment]
Trying to decide on an instance type for OMK.

## Stack requirements
The stack is only bound by the disk size. It works really well on a single CPU, and low memory, as shown in the above comment.

## Current instance type
From https://www.ec2instances.info/?selected=t2.large,t2.small,t2.medium,m3.medium:
Our current instances cost around so:
• `t2.small` uses 12 GB + 8 GB EBS. So, we pay something like 0.023/hour of usage + 12 * 0.1 + 8 * 0.1 per month. (5 stacks)
• `t2.medium` uses 12 GB + 8 GB EBS. So, we pay something like 0.0464/hour of usage + 12 * 0.1 + 8 * 0.1 per month. (Tanzania)
• * `t2.large` uses 12 GB + 8 GB EBS. So, we pay something like 0.0928/hour of usage + 12 * 0.1 + 8 * 0.1 per month. (Nepal)

T2 instances are burstable instances. They perform at a baseline CPU, and only offer bursts in performance when a large number of requests come in. Note that the baseline CPU performance is very small, 10% to 20% of the overall CPU potential: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-credits-baseline-concepts.html

## Instance type I used in experiments
 An instance I used for my experiments was the m3.medium with no additional EBS. This costs 0.067/hour of usage and does not require any EBS. It performs really well as well.

Per chat with @smit1678 and @ramyaragupathy, we are going to use the `t2` instances + EBS on our CloudFormation stacks for now. We can shift to other instance types after we do some work on cost analysis across our stacks.

**Comment by arunasank** [comment]
We decided to go ahead with the `c5d.large` as the first iteration on the production stacks.

**Comment by arunasank** [comment]
This happened as part of https://github.com/hotosm/OpenMapKitServer/pull/91 with @willemarcel and @ramyaragupathy. 💃
