### ISSUE TITLE
Direct HTTPS requests to OMK fail

### ISSUE THREAD

**Issue by arunasank** [hotosm/OpenMapKitServer#106]
Direct HTTPS requests to OMK fail. I verified this by directing HTTPS requests directly to the EC2 server, and directing them via the load balancer. Only way to enable HTTPS requests is by setting up both HTTPS and HTTP listeners, and converting the HTTPS requests to HTTP between the ELB and the EC2s.

Is there a reason for this on the application side? Or is it more an infrastructure issue?

cc/ @hotosm/tech

**Comment by arunasank** [comment]
Definitely seems like more of an issue on the infrastructure side, but I remember @smit1678 and @willemarcel talking about HTTP redirects failing. I want to know what exactly was the issue, and what did you try?

**Comment by smit1678** [comment]
good question @arunasank. We had previously set up this, https://github.com/hotosm/omk-server-eb/blob/master/.ebextensions/02_https.config. When it was deployed, forwarding traffic from http to https worked via web browser but it was the ODK Collect app that users ran into issues with it not working.

**Comment by willemarcel** [comment]
Issue finally solved and code merged! Thanks, @arunasank !!!
