### ISSUE TITLE
Restart OMK server automatically when it crashes

### ISSUE THREAD

**Issue by arunasank** [hotosm/OpenMapKitServer#112]
Currently, any of the requests in https://github.com/hotosm/OpenMapKitServer/issues/108 cause the OMK server to crash, and require the server to be restarted manually.

We are exploring options to get the server to restart automatically, starting with `pm2`.

cc/ @hotosm/tech

**Comment by willemarcel** [comment]
I proposed a solution to this on https://github.com/hotosm/OpenMapKitServer/pull/113

**Comment by willemarcel** [comment]
the solution is applied
