### ISSUE TITLE
Add auto-terminate to CloudFormation template

### ISSUE THREAD

**Issue by willemarcel** [hotosm/OpenMapKitServer#118]
When we update a CloudFormation instance, the old version of the EC2 is not being terminated and a new one started. So we need to add auto-terminate to the cfn template start a new EC2 instance when a update is pushed.

**Comment by arunasank** [comment]
Related: https://github.com/hotosm/tasking-manager/issues/1456

Working on fixing ^. We can apply the same fix to OMK, once that's done. 👍
