### ISSUE TITLE
Table view updates

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#12]
From a review running the `react-frontend` branch locally:

* Change label `OMK Data` to `ODK Data`
* Add filter by `Device ID` to enable filtering by user
* Add additional columns to table: 
  - non-OSM questions if available
  - link to image if collected
* Add Clear/reset filtered view
* When filtered, selecting download ODK or OSM should only download the filtered view

**Comment by willemarcel** [comment]
Done:
* Change label OMK Data to ODK Data
* Add filter by Device ID to enable filtering by user
* Add Clear/reset filtered view
* link to image if collected

Working now to filter the content when downloading.

@smit1678, about the non-OSM questions, do you have some form example?

**Comment by smit1678** [comment]
👍 Thanks @willemarcel. Sample forms sent via Slack.

**Comment by willemarcel** [comment]
All issues were already solved.
