### ISSUE TITLE
failing to fetch correct pyxform version

### ISSUE THREAD

**Issue by willemarcel** [hotosm/OpenMapKitServer#127]
I updates the pyxform repository to https://github.com/XLSForm/pyxform (the previous repository was deleted from github), but it's failing to fetch with `git submodule update --init`

```
Submodule 'api/odk/pyxform' (https://github.com/XLSForm/pyxform) registered for path 'api/odk/pyxform'
Cloning into '/tmp/OpenMapKitServer/api/odk/pyxform'...
error: Server does not allow request for unadvertised object e486b54d34d299d54049923e03ca5a6a1169af40
Fetched in submodule path 'api/odk/pyxform', but it did not contain e486b54d34d299d54049923e03ca5a6a1169af40. Direct fetching of that commit failed.
```

**Comment by eternaltyro** [comment]
@willemarcel try doing `git submodule sync` and see if that helps.

**Comment by willemarcel** [comment]
> @willemarcel try doing `git submodule sync` and see if that helps.

Thanks, @eternaltyro, but it didn't solve the problem

**Comment by willemarcel** [comment]
Fixed with https://github.com/hotosm/OpenMapKitServer/pull/128

Solved by installing pyxform from pip and using a node `child` process to execute `xls2xform`
