### ISSUE TITLE
Is achieve downloading url is correct in the documentation

### ISSUE THREAD

**Issue by KavinduZoysa** [hotosm/OpenMapKitServer#129]
In this [documetation](https://github.com/hotosm/OpenMapKitServer/blob/master/docs/posm-build-installation.md#steps) the downloading url is `https://github.com/AmericanRedCross/posm-build/archive/master.tar.gz`. Is this correct? Shouldn't it be `https://github.com/hotosm/posm-build/archive/master.tar.gz` ?

**Comment by willemarcel** [comment]
Hi @KavinduZoysa ! Thanks for the feedback. I just updated it
