### ISSUE TITLE
Some urls of OMK server are not working

### ISSUE THREAD

**Issue by KavinduZoysa** [hotosm/OpenMapKitServer#130]
I deployed the OMK server in Amazon following this [documentation](https://github.com/hotosm/OpenMapKitServer/blob/master/docs/posm-build-installation.md#steps). After that the following URLs mentioned in this [documentation](https://github.com/hotosm/OpenMapKitServer) are not working. 

http://{{your_host_url}}/omk/info
http://{{your_host_url}}/omk/pages/#/upload-form

Kindly request your help to solve this issue. I am a new person to this area.

**Comment by willemarcel** [comment]
@KavinduZoysa These URLs are correct. `/omk/info/` returns a JSON file with some information about the server. `/omk/pages/#/upload-form` needs to log in first to be seen.

**Comment by willemarcel** [comment]
@KavinduZoysa if you deployed it with posm-build, probably the urls are a bit different.

**Comment by KavinduZoysa** [comment]
Thank you @willemarcel. What is the document I need to follow? 

I followed this https://github.com/hotosm/OpenMapKitServer/blob/master/docs/posm-build-installation.md. Is it wrong?

This is the URL of my odk server http://3.136.100.53/. Appreciate if you can check that.

**Comment by willemarcel** [comment]
@KavinduZoysa Sorry, I don't have too much knowledge about POSM. If you really need all the tools on POSM, I suggest you to ask for support on https://github.com/posm/posm-build/

If you just need OpenMapKitServer, try with the Dockerfile or see the installation instructions:
https://github.com/hotosm/OpenMapKitServer/blob/master/Dockerfile
https://github.com/hotosm/OpenMapKitServer/blob/master/docs/development-installation.md

**Comment by KavinduZoysa** [comment]
@willemarcel thank you for your quick response. Initially, I get the support from POSM and this is the issue I created https://github.com/posm/OpenMapKitServer/issues/129. They have pointed me to this repo and I installed OMK server again by following the readme of this repo. 

Yes, as you mentioned I just need to install OMK server. So I prefer to run this docker file in my instance. Kindly request the instruction if possible :-)

**Comment by KavinduZoysa** [comment]
@willemarcel , is there any place where I can find the docker image?

**Comment by KavinduZoysa** [comment]
@willemarcel, First of all, thanks a lot for your support. By running the DockerFile I was able to start the OMK server. 

I have another question. To log in I used admin:admin as username and password. Is that correct?

**Comment by willemarcel** [comment]
@KavinduZoysa you can set the users on https://github.com/hotosm/OpenMapKitServer/blob/master/util/users.json . More information about authentication: https://github.com/hotosm/OpenMapKitServer/blob/master/docs/development-installation.md#users-and-roles.

When deploying with Docker, take a special attention to setup a S3 Bucket and enable the S3 sync, that way you have your data copied to S3 after each operation. You can start the S3 bucket with the content of the data dir here on the repository. Docs: https://github.com/hotosm/OpenMapKitServer/blob/master/docs/development-installation.md#data-sync

**Comment by KavinduZoysa** [comment]
@willemarcel Thanks a lot for your great support.

 I am closing this issue since the issue mentioned in the title was able to fix. Will get back if I found any unclear thing.
