### ISSUE TITLE
Download OSM file of filtered view results in no file

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#14]
When on a filtered view within the submissions table, selecting download OSM data results in failed, no file. This is via Chrome. 

Log output: 
```
::ffff:172.17.0.1 - - [20/Mar/2018:10:55:47 +0000] "GET /omk/odk/submissions/uganda_wash.osm&date=2017-09-01& HTTP/1.1" 404 199 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
```

**Comment by smit1678** [comment]
This also happens with an unfiltered view

**Comment by willemarcel** [comment]
The download OSM data is not yet filtered, but it had a wrong character that was causing the error. Fixed with https://github.com/hotosm/OpenMapKitServer/commit/59da0b47215ab3d17290bbe0c62d03e3fde0fe92

**Comment by smit1678** [comment]
@willemarcel great, thanks. Now seeing that it is a `.xml` extension. I think we need to do `.osm` right?

**Comment by willemarcel** [comment]
I believe all the `.osm` downloads are working correctly now.
