### ISSUE TITLE
Add form archive or delete button

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#17]
As an admin, I want to be able to delete a form I just uploaded (that doesn't have any submissions) or archive an older form (one that has submissions).

The question is what does this archive process look like? Does the user get a zip archive to download and save? Or do we just have an archive view of forms that have submissions to simplify the main view of "active" forms on the current landing page?

**Comment by willemarcel** [comment]
> The question is what does this archive process look like?

The best solution I thought is, when archiving:
* Move the form and its submissions to a separate folder;
* Create a view that lists the forms and how much submissions each of them has (something simple, without the possibility to see the submissions);
* A button to reactivate the form (it would just move the files to the default folders).

**Comment by danbjoseph** [comment]
I think I'd like the ability to download the data for an archived form without having to reactivate it.

**Comment by willemarcel** [comment]
Added in https://github.com/hotosm/OpenMapKitServer/commit/cdecbf451b1b34683e2c6451e621f2cae50f197e
