### ISSUE TITLE
Filter by deviceID improvements

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#18]
As a admin or dataviewer, I want to quickly select a deviceID to filter upon. 

Couple ideas for filter by device ID: 

1. Make table selectable (copy and paste doesn't work at the moment)
2. Dump available deviceIDs into a dropdown so a user can select

**Comment by willemarcel** [comment]
> Dump available deviceIDs into a dropdown so a user can select

done in https://github.com/hotosm/OpenMapKitServer/commit/35360ff36e46b021582afae91d713c310af6a312
