### ISSUE TITLE
Remove/de-emphasize Submit to OSM button

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#19]
Discussed this with @mojodna and @willemarcel last week. Submit to OSM button is prominent at the top. Is this function used a lot?

Most users (from our discussions) download the data, clean and process the data offline, and then submit via JOSM. Having the button prominently at the top seems to run the risk of users accidentally selecting the button and pushing to OSM. 

Do we want to reconsider this functionality or location of the button? 

thoughts @danbjoseph?

**Comment by danbjoseph** [comment]
I didn't even realize submitting to OSM was a current functionality? I thought POSM replay tool was more technical and required command line tools?

**Comment by PaulUithol** [comment]
Well, we can't really tell if it actually works at the moment, not much feedback to pushing the button ;)

**Comment by mojodna** [comment]
It was originally intended for pushing to POSM's OSM instance so that subsequent editing could be done against the (local) API. I don't think that workflow is used / useful though.

**Comment by willemarcel** [comment]
Removed in https://github.com/hotosm/OpenMapKitServer/commit/cdecbf451b1b34683e2c6451e621f2cae50f197e
