### ISSUE TITLE
Filter by username instead of deviceid

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#21]
Feedback from users. Consider using `username` instead of `deviceid`.

These are [metadata fields that need to be setup in the xlsform](http://xlsform.org/#metadata). Deviceid is nice because it doesn't require the user to set it up when setting up ODK Collect. Username is a metadata field that can be added as a metadata item. It grabs the username that is setup when adding the server information in ODK Collect. 

For OMK Server, it doesn't necessarily require auth to submit forms, but you can add a username (password does not need to be filled in and this could also just be the OSM username) and it'll be tracked in submission. This can then be used to filter instead of deviceid. This would make this filtering feature much more user friendly and not require a separate sheet of ids to track.

**Comment by danbjoseph** [comment]
could there be a dropdown to select the field to filter on?

users might be using `deviceid`, `username`, `subscriberid`, `simserial`, `phonenumber`, or a custom field (e.g. a select_one for `enumerator` or some such). 

choosing the field to filter on would also allow users to export only submissions for a certain administrative area or some such.

**Comment by smit1678** [comment]
@willemarcel and I talked about this and we were thinking that the best option is to allow filtering on any type of field in the data. Then that solves the variety of use cases. 

I think for the near-term solution we're going to switch to `username` as an option and then improve from there.

**Comment by willemarcel** [comment]
done in https://github.com/hotosm/OpenMapKitServer/commit/47ed9637a2a5687b9df4aac89f4d184efb15d1fa

It will show the `username` field and filter by it, if the form has that field, otherwise it will use the `deviceId`.
