### ISSUE TITLE
Long form name title overflows form card

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#28]
![openmapkit server 2018-04-11 10-46-09](https://user-images.githubusercontent.com/796838/38606202-a7e0fda0-3d75-11e8-9125-a827f6d3aa2a.png)

**Comment by willemarcel** [comment]
Solved with https://github.com/hotosm/OpenMapKitServer/commit/824bdd82e1334cbaef9486346e5dabb087a87a15
