### ISSUE TITLE
ODK only forms raise TypeError

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#29]
Submitting to ODK only (no OSM collection) forms works smoothly and shows that there are submissions within the form on the main form view. But when clicking to View Submissions, a TypeError is raised and the page does not load. 

My assumption is that this is due to the fact there is no `.osm` file that is accompanying the `data.json` and `data.xml` files for the submission. 

![openmapkit server 2018-04-11 10-48-57](https://user-images.githubusercontent.com/796838/38606348-0a567262-3d76-11e8-9abb-035f58cfa01a.png)

**Comment by willemarcel** [comment]
I believe I solved it with https://github.com/hotosm/OpenMapKitServer/commit/63e0939a64229410e26435290068414b6806b68b

If the problem persists, could you share a zip file with the form and submissions files with me?

**Comment by smit1678** [comment]
Looks like it fixed it. Will monitor and make sure as submissions come in.
