### ISSUE TITLE
Sketch out data management UI improvements

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#3]
From https://github.com/hotosm/tech/issues/98

Look to improve data management functions for forms and submitted data. Need to consider: 
  * sort, filter, export by day and user
  * update, delete forms
  * consider some features that other ODK-based tools do

**Comment by smit1678** [comment]
@danbjoseph @dalekunce Have either of you conducted some initial design work when thinking about the above?

**Comment by danbjoseph** [comment]
i'm not real happy with the forms interface in general right now.
and the data interface is meh.
i'd be fine with a complete overhaul of both.
but haven't thought much about it yet.

**Comment by danbjoseph** [comment]
An interface showing completed data exports available for download should be sure to have complete metadata easily visible (e.g. date/time of export, any filter settings, etc.). Could be interesting to either include a metadata text file zipped with the data export or somehow include it in the file itself (for example.. if an xlsx then on an additional worksheet, if a csv then at the bottom after a line break).

**Comment by PaulUithol** [comment]
@smit1678 was work on this starting this week? Can we still add the ability to "archive" submissions (based on certain filer criteria)? Or is improving performance when there's a large number of submissions also on the list?

**Comment by willemarcel** [comment]
I believe everything is done
