### ISSUE TITLE
Upload form not working on geojson-endpoint branch

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#51]
@willemarcel running into some upload form errors on the `geojson-endpoint` branch. Seeing bad requests to the https://omk-test.hotosm.org/omk/odk/upload-form endpoint. Is this something we need to configure within the deployment related to the recent url changes? 

<img width="1371" alt="openmapkit server 2018-08-22 14-49-20" src="https://user-images.githubusercontent.com/796838/44450443-23d09480-a61b-11e8-8db6-a5068020d58a.png">

**Comment by willemarcel** [comment]
@smit1678 I succeeded upload a form: https://omk-test.hotosm.org/omk/pages/#/submissions/RH_Shops_and_Markets_V6

Could you send me the files that you tried to upload? Have you tried to upload more than one in a time?

**Comment by willemarcel** [comment]
@smit1678 closing this. Reopen if something deserves our attention on this topic
