### ISSUE TITLE
Show ODK only surveys with geopoint information on map

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#53]
ODK only surveys (without any OSM data) don't show on map. These surveys have a geopoint information. 

Example: http://zambia.hotosm.org/omk/pages/#/submissions/Zambia_Minigrid_Village_Survey_V02

**Comment by rishabhkalra96** [comment]
hi
can you give me some more information on this issue and what is expected.

**Comment by willemarcel** [comment]
Solved with https://github.com/hotosm/OpenMapKitServer/pull/107/commits/55f26af71704723c115034c4b3bc050bb7eb5666
