### ISSUE TITLE
No image shown in submissions table

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#54]
In an ODK survey, no image is shown in the submissions table even though the image exists. This is part of a survey that collects an image. When clicking download attachments, the images are downloaded. 

<img width="1385" alt="openmapkit server 2018-08-28 08-20-02" src="https://user-images.githubusercontent.com/796838/44702255-37f11780-aa9b-11e8-829b-c9d0abfae059.png">

**Comment by willemarcel** [comment]
This form image is not stored in the `image` field but as `village_picture`: http://zambia.hotosm.org/omk/data/submissions/Zambia_Minigrid_Village_Survey_V02/a6ba2370-4432-43ff-9ff3-287228a0c541/data.json

Do you think we can instruct the users to set the image field as "image" in the form?

**Comment by smit1678** [comment]
> Do you think we can instruct the users to set the image field as "image" in the form?

That's a good catch. Thanks @willemarcel. You're probably right, we should provide documentation that it needs to be the image field. I'm not sure there is another way to grab the field type instead of the name but I think that makes sense.

**Comment by willemarcel** [comment]
I think it's better to set the image field. The users can add more than one image field, so it wouldn't solve the problem and it would be more complicated to handle.
