### ISSUE TITLE
Add new features CSV endpoint

### ISSUE THREAD

**Issue by willemarcel** [hotosm/OpenMapKitServer#56]
Add endpoint to list the features submitted to OMK-Server as CSV. It doesn't need to include the geometry, just the attributes that were collected.

**Comment by PaulUithol** [comment]
@willemarcel as I understand from @jessbeutler, this isn't quite resolved yet, as the CSV export only exposes OMK data (and not related ODK attributes). Is there a separate issue for this?

**Comment by willemarcel** [comment]
Hi @PaulUithol 

I just added the ODK attributes to the geojson and CSV endpoints: https://github.com/hotosm/OpenMapKitServer/pull/68

Note that the CSV endpoint doesn't work with ODK only surveys yet.
