### ISSUE TITLE
Rename download buttons

### ISSUE THREAD

**Issue by willemarcel** [hotosm/OpenMapKitServer#65]
![screenshot_2018-10-04 openmapkit server](https://user-images.githubusercontent.com/666291/46481653-3d442f00-c7ca-11e8-9a66-653f62c37a63.png)

I have some suggestions about the download buttons:

* The `ODK Data` could be renamed to `Submissions` and the internal links:
  * Submissions as CSV
  * Submissions as JSON
  * Attached Files
* The `OSM Data` could be `Geospatial data` or `Map data` and the internal links: 
  * All data as OSM
  * Filtered data as OSM
  * All data as GeoJSON
  * Filtered data as GeoJSON
  * All data as CSV
  * Filtered data as CSV

See https://github.com/hotosm/OpenMapKitServer/issues/56, about the CSV files.

What do you think, @smit1678 @mojodna?

**Comment by jessbeutler** [comment]
I agree with your suggestion, @willemarcel - that would make a lot more sense to users that are new to OMKServer or are not as familiar with the data types.

**Comment by PaulUithol** [comment]
Does "filtered data" as such also apply to the ODK data/submissions? Or does that not have filtering?

**Comment by willemarcel** [comment]
@PaulUithol yes, it applies.
