### ISSUE TITLE
"Access to submissions is restricted to admin and data-viewer users." message persists after data loads

### ISSUE THREAD

**Issue by mojodna** [hotosm/OpenMapKitServer#9]
E.g.

<img width="1240" alt="screen shot 2018-02-12 at 12 16 49 pm" src="https://user-images.githubusercontent.com/45/36117524-c1362942-0fee-11e8-9e20-c98293e3fb8f.png">

(See bottom)

**Comment by willemarcel** [comment]
I fixed it on https://github.com/hotosm/OpenMapKitServer/commit/317c883e5b5536219be6623b1757dd693fd811d1

thanks for the report, @mojodna !
